timApp/gamification/routes.py

Fix groups_badges route to fetch multiple badges with identical ids

Fix groups_badges route to fetch multiple badges with identical ids

---

timApp/static/scripts/tim/Badge/badge-creator.component.ts
timApp/static/scripts/tim/Badge/badge-giver.component.ts
timApp/static/scripts/tim/Badge/badge.interface.ts
timApp/static/scripts/tim/Badge/badge.service.ts

* remove unnecessary interfaces from components

Move IBadge interface to separate file

---

timApp/static/scripts/tim/Badge/badge-giver.component.html
timApp/static/scripts/tim/Badge/badge-giver.component.ts
timApp/static/scripts/tim/Badge/badge-viewer-component.ts

* add placeholders for user and badge selection

Fix bug when loading badges

---

timApp/static/scripts/tim/gamification/badge/badge-giver.component.html
timApp/static/scripts/tim/gamification/badge/badge-giver.component.ts
timApp/static/scripts/tim/gamification/badge/badge-viewer.component.ts

Badge-viewer and badge-giver now display full name instead of username

display user's full name instead username

---

timApp/defaultconfig.py
timApp/gamification/badge/routes.py

Move badge.log in tim_logs folder.

Backend: move log file

---

timApp/static/scripts/tim/gamification/badge/badge-creator.component.ts

Added tim confirmation dialog to badge-creator when editing or deleting badge

Confirm dialog when editing or deleting badge

---

timApp/static/scripts/tim/gamification/badge/badge-creator.component.scss
timApp/static/scripts/tim/gamification/badge/badge-creator.component.ts

This commit will make the badge creator buttons work correctly when clicking depending if creating a new badge or editing an existing one.

Creator buttons

---

timApp/gamification/badge/routes.py

Fix route not to fetch the exact prefix.

subgroups route: Fix to not fetch the exact prefix

---

timApp/static/scripts/tim/gamification/badge/badge-giver.component.ts
timApp/static/scripts/tim/gamification/badge/badge.service.ts

badge-giver: Refactor badge-giver to use http get methods from badge-service
badge-service: Add getUsersFromGroup and getSubGroups methods

Badge service refactor

---

timApp/static/scripts/tim/gamification/badge/badge-creator.component.scss
timApp/static/scripts/tim/gamification/badge/badge-creator.component.ts
timApp/static/scripts/tim/gamification/badge/badge-viewer.component.scss
timApp/static/scripts/tim/gamification/badge/badge.component.scss

Improved badge, badge-viewer and badge-creator styles

Improved badge styles

---

timApp/static/scripts/tim/gamification/badge/badge-giver.component.ts

Change delete button visibility when assigning a badge

Hide remove button when a badge is chosen from assign list

---

timApp/static/scripts/tim/gamification/badge/badge-giver.component.ts

Resets badge assigning field when changing user or group

reset Badge to Assign -field when changing user or group

---

timApp/static/scripts/tim/gamification/badge/badge-giver.component.ts

Fixed a bug that caused group field to reset when choosing a badge to be assigned

Fix bug that prevented assigning a badge to group

---

timApp/static/scripts/tim/gamification/badge/badge-creator.component.ts
timApp/static/scripts/tim/gamification/badge/badge-giver.component.ts
tim_common/html_sanitize.py

html_sanitizer: Add badge-group
badge-creator: Add Give badge option
Resolve merge errors

Badge creator merge

---

timApp/static/scripts/tim/gamification/badge/badge-creator.component.ts
timApp/static/scripts/tim/gamification/badge/badge-withdraw.component.scss
timApp/static/scripts/tim/gamification/badge/badge-withdraw.component.ts
timApp/static/scripts/tim/main.ts
tim_common/html_sanitize.py

Add new component: badge-withdraw.component.ts and badge-withdraw.component.scss
Add doDowngrade for badge-withdraw.component in main.ts
Add withdraw badge option in badge-creator
Remove withdraw option from badge-giver

Add new component: badge-withdrawand option to withdraw badge in creator

---

timApp/gamification/badge/routes.py
timApp/static/scripts/tim/gamification/badge/badge-creator.component.ts
timApp/static/scripts/tim/gamification/badge/badge-giver.component.ts
timApp/static/scripts/tim/gamification/badge/badge.service.ts

Add teacher verification for badge routes and modify route calls according to it.

Backend access rights for teachers

---

timApp/gamification/badge/routes.py
timApp/static/scripts/tim/gamification/badge/badge-creator.component.ts
timApp/static/scripts/tim/gamification/badge/badge-viewer.component.ts
timApp/static/scripts/tim/gamification/badge/badge-withdraw.component.ts
timApp/static/scripts/tim/gamification/badge/badge.service.ts

Add user's subgroup's badges in badge-viewer

Badge viewer groups

---

timApp/static/scripts/tim/gamification/badge/badge-withdraw.component.scss
timApp/static/scripts/tim/gamification/badge/badge-withdraw.component.ts

Add highlights to selected badges in badge-withdraw-component

badge-withdraw-component: Highlight selected badge

---

timApp/gamification/badge/badges.py
timApp/gamification/badge/routes.py

Sort badges and badgegivens correctly when fetching them from database.

Sort badges and badgegivens correctly when fetching them from database

---

timApp/static/scripts/tim/gamification/badge/badge-creator.component.ts
timApp/static/scripts/tim/gamification/badge/badge-withdraw.component.ts

Fix badge-withdraw cancel function by adding cancelEvent

Badge withdraw cancel

---

timApp/gamification/badge/routes.py

Add route for getting personal usergroup of given useraccount.

Add route for getting personal usergroup of given useraccount

---

timApp/static/scripts/tim/gamification/badge/badge-giver.component.ts
timApp/static/scripts/tim/gamification/badge/badge.service.ts

Changes user's personal ID to user's personal group's ID when assigning a badge to user

Add personalGroup fetcher to badge service and giver

---

timApp/gamification/badge/routes.py
timApp/static/scripts/tim/gamification/badge/badge.service.ts

Add usergroups_members-route that fetches members of given usergroup.

Add usergroups_members-route that fetches members of given usergroup

---

timApp/static/scripts/tim/gamification/badge/badge-giver.component.ts
timApp/static/scripts/tim/gamification/badge/badge-viewer.component.ts

Fix fetching of given badges in viewer and giver to fetch based on personal usergroup id instead of useraccount id.

Fix fetching of given badges

---

timApp/static/scripts/tim/gamification/badge/badge-withdraw.component.ts

Fix fetching of given badges in withdraw to fetch based on personal usergroup id instead of useraccount id.

Fix fetching of given badges in withdraw

---

timApp/gamification/badge/routes.py
timApp/tests/server/test_badges.py

Add simple backend tests for badges.

Backend tests

---

timApp/gamification/badge/routes.py

Fix routes to handle context_group correctly except modify_badge-route.

Fix routes

---

timApp/gamification/badge/routes.py

Fix modify_badge route and modify check_context_group_access to deal with context_group as int.

Fix modify_badge route

---

timApp/gamification/badge/routes.py
timApp/static/scripts/tim/gamification/badge/badge-giver.component.ts
timApp/static/scripts/tim/gamification/badge/badge-viewer.component.ts
timApp/static/scripts/tim/gamification/badge/badge-withdraw.component.ts
timApp/static/scripts/tim/gamification/badge/badge.service.ts

Refactor user_and_personal_group route to fetch also user in addition to personal group.

Refactor user_and_personal_group route

---

timApp/static/scripts/tim/gamification/badge/badge-viewer.component.ts
timApp/static/scripts/tim/gamification/badge/badge-withdraw.component.ts
timApp/static/scripts/tim/gamification/badge/badge.interface.ts
timApp/static/scripts/tim/gamification/badge/badge.service.ts
tim_common/html_sanitize.py

Add badge-viewer and badge-withdraw to use IPersonalGroup interface

Badge viewer context merge

---

timApp/gamification/badge/routes.py

Fix badge related teacher access verifications so that verification is based on usergroup's teacher access.

Fix badge related teacher access verifications

---

timApp/static/scripts/tim/gamification/badge/badge-withdraw.component.scss
timApp/static/scripts/tim/gamification/badge/badge-withdraw.component.ts

Modify UI to look and function similar with badge-giver-component

Badge withdraw UI

---

timApp/gamification/badge/routes.py

Modify groups_badges-route to return more attributes.

Modify groups_badges-route

---

timApp/gamification/badge/routes.py
timApp/static/scripts/tim/gamification/badge/badge.service.ts
timApp/static/scripts/tim/gamification/badge/group-name.component.ts
timApp/static/scripts/tim/main.ts
timApp/static/scripts/tim/ui/tim-utility.module.ts
tim_common/html_sanitize.py

Adds group name changer component that allows user to view his/her current group name and change it

Group name changer

---

timApp/gamification/badge/routes.py

Modify check_context_group_access to use get_current_user_object instead of user-id from frontend.

Modify check_context_group_access

---

timApp/gamification/badge/routes.py
timApp/static/scripts/tim/gamification/badge/badge.service.ts

Add groups_badges-route access rights check and refactor check_group_member-function.

Add groups_badges-route access rights check

---

timApp/gamification/badge/routes.py

Fix access right checks so that teachers don't need to be in context_groups anymore.

Fix access right checks

---

timApp/static/scripts/tim/gamification/badge/badge-giver.component.ts
timApp/static/scripts/tim/gamification/badge/badge.service.ts

badge-giver: Fix user-selection bugs in user-view

Badge giver fixes

---

timApp/gamification/badge/routes.py
timApp/static/scripts/tim/gamification/badge/group-name.component.ts

Change getGroupName function to fetch pretty name, remove unused implementations

Name changer

---

timApp/gamification/badge/routes.py
timApp/static/scripts/tim/gamification/badge/badge-creator.component.ts

Add route for fetching user groups with a certain badge.

Add route for fetching user groups with a certain badge

---

timApp/static/scripts/tim/gamification/badge/badge-viewer.component.ts

Formatted badge given time

---

timApp/gamification/badge/routes.py

Add route for withdrawing all badges with certain id from certain usergroup.

Add route for withdrawing all badges with certain id from certain usergroup

---

timApp/gamification/badge/routes.py

Modify badge_holders route so that it returns a list of users and a list of usergroups.

Modify badge_holders route

---

timApp/gamification/badge/routes.py
timApp/tests/server/test_badges.py

Fix badge tests

---

timApp/static/scripts/tim/gamification/badge/badge.leaderboard.scss
timApp/static/scripts/tim/gamification/badge/badge.leaderboard.ts

Edited leaderboard styling, leaderboard uses pretty group names now

Badge leaderboard

---

timApp/gamification/badge/routes.py
timApp/tests/server/test_badges.py

Add backend tests for creating, modifying and deleting badges.

Backend badge testing

---

timApp/static/scripts/tim/gamification/badge/badge-selected-withdraw.component.ts
timApp/static/scripts/tim/gamification/badge/badge.service.ts
timApp/static/scripts/tim/gamification/badge/group-name.component.ts

* remove unnecessary console logs from group's name fetching

display pretty group names when withdrawing badges from groups

---

timApp/static/scripts/tim/gamification/badge/badge-giver.component.scss
timApp/static/scripts/tim/gamification/badge/badge-giver.component.ts
timApp/static/scripts/tim/gamification/badge/badge-selected-withdraw.component.scss
timApp/static/scripts/tim/gamification/badge/badge-selected-withdraw.component.ts
timApp/static/scripts/tim/gamification/badge/badge-withdraw.component.scss
timApp/static/scripts/tim/gamification/badge/badge-withdraw.component.ts

Create scroll bar when list of users or groups is more than 300px

Add scrollbar to giver, withdraw and selected-withdraw components

---

timApp/static/scripts/tim/gamification/badge/badge.leaderboard.scss
timApp/static/scripts/tim/gamification/badge/badge.leaderboard.ts

the leaderboard will scale down if the window is smaller

Scaling leaderboard

---

timApp/static/scripts/tim/gamification/badge/badge-giver.component.scss
timApp/static/scripts/tim/gamification/badge/badge-giver.component.ts
timApp/static/scripts/tim/gamification/badge/badge-withdraw.component.ts

Add select all users and groups buttons in badge-giver and UI fixes

badge-giver: Add select all users and groups button and UI fixes

---

timApp/static/scripts/tim/gamification/badge/badge-creator.component.ts
timApp/static/scripts/tim/gamification/badge/badge.component.scss
timApp/static/scripts/tim/gamification/badge/badge.leaderboard.scss

Scss cleanup

---

timApp/gamification/badge/badges.py
timApp/gamification/badge/routes.py
timApp/tests/server/test_badges.py

Add more badge tests, fix groups_badges-route and add to_json-function to BadgeGiven.

Add more badge tests

---

timApp/gamification/badge/routes.py
timApp/static/scripts/tim/gamification/badge/badge-viewer.component.ts
timApp/tests/server/test_badges.py

Add backend tests for giving, withdrawing and fetching given badges.

Add backend tests

---

timApp/static/scripts/tim/gamification/badge/badge-giver.component.ts
timApp/static/scripts/tim/gamification/badge/badge-selected-withdraw.component.ts
timApp/static/scripts/tim/gamification/badge/badge-viewer.component.ts
timApp/static/scripts/tim/gamification/badge/badge-withdraw.component.ts

Refactor code and make checkbox unchecked when group/user's name is clicked again

Badge giver checkbox fix

---

timApp/gamification/badge/routes.py
timApp/static/scripts/tim/gamification/badge/badge-creator.component.ts
timApp/static/scripts/tim/gamification/badge/badge-giver.component.ts
timApp/static/scripts/tim/gamification/badge/badge-selected-withdraw.component.ts
timApp/static/scripts/tim/gamification/badge/badge-withdraw.component.ts
timApp/static/scripts/tim/gamification/badge/badge.service.ts
timApp/tests/server/test_badges.py

Remove unnecessary parameters from badge routes and refactor frontend according to that.

Refactor badge routes

---

timApp/static/scripts/tim/gamification/badge/badge-creator.component.ts
timApp/static/scripts/tim/gamification/badge/badge-viewer.component.ts
timApp/static/scripts/tim/gamification/badge/badge-withdraw.component.ts

Show backend error messages in badge-withdraw and adjust error messages in creator and viewer

Error messages

---

timApp/static/scripts/tim/gamification/badge/group-name.component.ts
timApp/static/scripts/tim/main.ts
timApp/static/scripts/tim/plugin/group-dashboard/group-dashboard.component.scss
timApp/static/scripts/tim/plugin/group-dashboard/group-dashboard.component.ts
tim_common/html_sanitize.py

Adds group's dashboard functionality that shows group's common badges, each member of the group and their personal badges. Also makes use of group's name changer tool in settings section.

Group document

---

timApp/gamification/badge/routes.py
timApp/static/scripts/tim/gamification/badge/badge-creator.component.ts
timApp/static/scripts/tim/gamification/badge/badge-viewer.component.ts
timApp/static/scripts/tim/gamification/badge/badge-withdraw.component.ts
timApp/user/groups.py

Add correct error messages to badge routes.

Add correct error messages to badge routes

---

timApp/static/scripts/tim/gamification/badge/badge-withdraw.component.ts

* fetch prettyNames via group service instead

remove old prettyGroupName function

---

timApp/tests/browser/test_badges.py

This merge will add browsertests for the creator component in the badges-file under gamification.

This commit will add browsertests for badge-creator-component.

---

timApp/gamification/badge/routes.py
timApp/tests/server/test_badges.py

Fix bug that caused to leaderboard to count nonactive badges.

Fix leaderboard bug

---

timApp/static/scripts/tim/plugin/group-dashboard/group-dashboard.component.scss
timApp/static/scripts/tim/plugin/group-dashboard/group-dashboard.component.ts

Add more information  and styling to group dashboard component

Group dashboard styling

---

timApp/static/scripts/tim/gamification/badge/badge-giver.component.scss
timApp/static/scripts/tim/gamification/badge/badge-giver.component.ts
timApp/static/scripts/tim/gamification/badge/badge-withdraw.component.ts

Visual changes in badge-giver user and group view and remove badges-preview

User and group view lists

---

timApp/gamification/badge/routes.py
timApp/tests/server/test_badges.py

Add tests for erroneous data and add error handling to badge routes.

Add tests and error handling

---

timApp/static/scripts/tim/gamification/badge/badge-giver.component.scss
timApp/static/scripts/tim/gamification/badge/badge-giver.component.ts
timApp/static/scripts/tim/gamification/badge/badge-withdraw.component.scss
timApp/static/scripts/tim/gamification/badge/badge-withdraw.component.ts

Add users with no group in withdraw component user view and small UI changes to withdraw and giver components.

Badge giver and withdraw UI

---

timApp/gamification/badge/badges.py
timApp/gamification/badge/routes.py
timApp/tests/server/test_badges.py
timApp/user/groups.py

Add tests for badge-routes using erroneous data and handling errors in those routes.

Add tests for badge-routes and handling errors in those routes

---

timApp/gamification/badge/routes.py
timApp/static/scripts/tim/gamification/badge/badge-creator.component.ts
timApp/static/scripts/tim/gamification/badge/badge-withdraw.component.ts
timApp/tests/server/test_badges.py

Move error message generation from frontend to backend and add error handling and backend tests for podium-route.

Enhancing error messages and podium-route

---

timApp/static/scripts/tim/main.ts
timApp/static/scripts/tim/plugin/group-dashboard/group-dashboard.component.ts
timApp/static/scripts/tim/plugin/group-dashboard/point-calculator.component.scss
timApp/static/scripts/tim/plugin/group-dashboard/point-calculator.component.ts
timApp/static/scripts/tim/plugin/group-dashboard/point.service.ts
tim_common/html_sanitize.py

Points component

---

timApp/gamification/badge/routes.py
timApp/tests/server/test_badges.py

Add access right checks to routes and add tests for them.

Add access right checks and tests

---

timApp/static/scripts/tim/gamification/badge/badge-withdraw.component.ts

Withdraw component now display group's pretty name also in preview window. Withdraw component also uses view centering when cancel button is clicked

Change group badge preview window to display pretty name

---

timApp/gamification/badge/routes.py
timApp/tests/server/test_badges.py
timApp/user/groups.py

Add error handling and access right checks to routes related to group name changer.

Add error handling and access right checks

---

timApp/static/scripts/tim/plugin/group-dashboard/group-dashboard.component.scss
timApp/static/scripts/tim/plugin/group-dashboard/group-dashboard.component.ts

Fixes to badge size in group dashboard

Dashboard fix

---

timApp/gamification/badge/routes.py

Fix access right check in usergroups_members-route.

Fix access right check in usergroups_members-route

---

timApp/static/scripts/tim/gamification/badge/badge-creator.component.ts

Add maxlength to title in badge-creator

---

timApp/gamification/badge/routes.py
timApp/tests/server/test_badges.py

Fix teacher access right check in every badge related route and refactor some of backend tests according to that.

Backend fix teacher access right checks

---

timApp/tests/server/test_badges.py
timApp/tests/server/test_groups.py
timApp/user/groups.py

Refactor backend badge erraneous data tests and add backend tests for group name changer.

Refactor and add backend badge tests

---

timApp/static/scripts/tim/gamification/badge/badge-withdraw.component.ts

Add error messages to withdraw-component.

Add error messages to withdraw-component
